stages:
  - build
  - publish

variables:
  BUCKET_NAME: ''

build:
  image: node:lts
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    name: build-output
    paths:
      - build/

.aws-cli:
  image:
    name: amazon/aws-cli:latest
    entrypoint:
      - '/usr/bin/env'

publish:
  stage: publish
  dependencies:
    - build
  extends: .aws-cli
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE  != "parent_pipeline"'
  script:
    - |
      aws s3 cp build s3://$OMBIT_WEBSITE_BUCKET --acl public-read --recursive
